CREATE TABLE Fornitore(
	pIVA NUMBER NOT NULL, 
	nome CHAR(50) NOT NULL,
	citta CHAR(50) NOT NULL,
	cap NUMBER NOT NULL,
	via VARCHAR2(50),

	CONSTRAINT FORN_PK
		PRIMARY KEY(pIVA)
);

CREATE TABLE MastroBirraio(
	ssn VARCHAR2(30) NOT NULL,
	nome CHAR(20) NOT NULL,
	cognome CHAR(20) NOT NULL,
	dataNascita DATE NOT NULL,
	dataAssunzione DATE NOT NULL,
	stipendio NUMBER NOT NULL CHECK(Stipendio >= 1000),
	
	CONSTRAINT MB_PK
		PRIMARY KEY(ssn)
);

CREATE TABLE Contenitore(
	id NUMBER GENERATED BY DEFAULT AS IDENTITY,
	ssnResponsabile VARCHAR(30),
	tipo CHAR(20) CHECK(tipo IN ('Bollitore' , 'Fermentatore')),
	capacitaLavorazione NUMBER,
	capacitaComplessiva NUMBER,
	potenza NUMBER,

	CONSTRAINT CONT_PK
		PRIMARY KEY(id),
	CONSTRAINT CONT_FK_MB
		FOREIGN KEY (ssnResponsabile) REFERENCES MastroBirraio(ssn)
);

CREATE TABLE OrdineApproviggionamento(
	codFattura NUMBER NOT NULL,
	pIvaFornitore NUMBER NOT NULL,
	dataRifornimento DATE NOT NULL,
	metodoPagamento VARCHAR (50),
	numeroTracking VARCHAR (50),

	CONSTRAINT OAPP_PK
		PRIMARY KEY(codFattura),
	CONSTRAINT OAPP_FK_FORN
		FOREIGN KEY(pIvaFornitore) REFERENCES Fornitore(pIVA)
		
);

CREATE TABLE MateriaPrima(
	GTIN NUMBER NOT NULL,
	tipo VARCHAR2(60),
	
	CONSTRAINT MAT_P_PK
		PRIMARY KEY(GTIN)
);


CREATE TABLE Malto(
	GTIN NUMBER NOT NULL,
	cerealeMaltato VARCHAR2(50) NOT NULL CHECK(cerealeMaltato IN ('Orzo','Segale','Frumento','Mais')),
	nomeMalto VARCHAR2(50),
	quantitaMagazzino NUMBER NOT NULL,
	provenienza VARCHAR2(60),
	
	CONSTRAINT MALT_PK 
		PRIMARY KEY(GTIN),
	CONSTRAINT MALT_PKFK
		FOREIGN KEY (GTIN) REFERENCES MateriaPrima(GTIN)
);

CREATE TABLE Luppolo(
	GTIN NUMBER NOT NULL,
	classificazione VARCHAR(50) NOT NULL,
	tipoLuppolo VARCHAR(50)  CHECK (tipoLuppolo IN ('Amaricante','Aromatizzante','Misto')),
	quantitaMagazzino NUMBER NOT NULL,
	provenienza VARCHAR2(60),
	
	CONSTRAINT LUPP_PK 
		PRIMARY KEY(GTIN),
	CONSTRAINT LUPP_PKFK
		FOREIGN KEY (GTIN) REFERENCES MateriaPrima(GTIN)
);

CREATE TABLE Lievito(
	GTIN NUMBER NOT NULL,
	tipoLievito VARCHAR(50) NOT NULL CHECK (tipoLievito IN ('Saccharomyces Cerevisiae','Saccharomyces Carlsbergensis')),
	quantitaMagazzino NUMBER NOT NULL,
	provenienza VARCHAR2(60),

	CONSTRAINT LIEV_PK 
		PRIMARY KEY(GTIN),
	CONSTRAINT LIEV_PKFK
		FOREIGN KEY (GTIN) REFERENCES MateriaPrima(GTIN)
);

CREATE TABLE LottoMateriaPrima(
	codiceLotto VARCHAR2(50) NOT NULL,
	GTIN NUMBER NOT NULL,
	codFattura NUMBER NOT NULL,
	prezzoAcquisto NUMBER NOT NULL,
	
	CONSTRAINT LMAT_P_PK
		PRIMARY KEY(GTIN,codiceLotto),
	CONSTRAINT LMAT_P_FK_MAT_P
		FOREIGN KEY(GTIN) REFERENCES MateriaPrima(GTIN),
	CONSTRAINT LMAT_P_FK_OAPP
		FOREIGN KEY(codFattura) REFERENCES OrdineApproviggionamento(codFattura)	
);

CREATE TABLE MaltoAcquistato(
	GTIN NUMBER NOT NULL,
	codiceLotto VARCHAR2(50) NOT NULL,
	idBollitore NUMBER,
	
	CONSTRAINT MALTOACQ_PK
		PRIMARY KEY(GTIN,codiceLotto),
	CONSTRAINT MALTOACQ_ORDER_PK_FK	
		FOREIGN KEY(GTIN,codiceLotto) REFERENCES LottoMateriaPrima(GTIN,codiceLotto) ON DELETE CASCADE,
	CONSTRAINT MALTOACQ_IDB_FK
		FOREIGN KEY(idBollitore) REFERENCES Contenitore(id)

);

CREATE TABLE LuppoloAcquistato(
	GTIN NUMBER NOT NULL,
	codiceLotto VARCHAR(50) NOT NULL,
	
	CONSTRAINT LUA_PK
		PRIMARY KEY(GTIN,codiceLotto),
	CONSTRAINT LUPPACQ_ORDER_PKFK	
		FOREIGN KEY(GTIN,codiceLotto) REFERENCES LottoMateriaPrima(GTIN,codiceLotto)
);

CREATE TABLE LievitoAcquistato(
	GTIN NUMBER NOT NULL,	
	codiceLotto VARCHAR2(50) NOT NULL,
	
	CONSTRAINT LA_PK
		PRIMARY KEY(GTIN,codiceLotto),
	CONSTRAINT LA_ORDER_PKFK	
		FOREIGN KEY(GTIN,codiceLotto) REFERENCES LottoMateriaPrima(GTIN,codiceLotto)
);



CREATE TABLE MostoDolce(
	numLotto NUMBER GENERATED BY DEFAULT AS IDENTITY,
	gtinLuppoloUsato NUMBER NOT NULL,
	codLottoLuppolo VARCHAR(50) NOT NULL,
	idBollitore NUMBER NOT NULL,
	quantitaLuppoloUsato NUMBER,
	gradiPlato NUMBER CHECK (gradiPlato > 0),
	quantitaMosto NUMBER CHECK (quantitaMosto > 0),
	
	CONSTRAINT MD_PK
		PRIMARY KEY(numLotto),
	CONSTRAINT MD_LUP_FK
		FOREIGN KEY(gtinLuppoloUsato,codLottoLuppolo) REFERENCES LuppoloAcquistato(GTIN,codiceLotto),
	CONSTRAINT MD_CONT_FK
		FOREIGN KEY(idBollitore) REFERENCES Contenitore(id)
);

CREATE TABLE BirraProdotta(
	numLotto NUMBER GENERATED BY DEFAULT AS IDENTITY,
	ssnSupervisore VARCHAR2(16) NOT NULL,
	numLottoMostoDolce NUMBER NOT NULL, 
	GTIN NUMBER NOT NULL,
	nomeBirra VARCHAR2(50) NOT NULL,
	gradoAlcolico NUMBER NOT NULL CHECK(gradoAlcolico >= 0),
	colore VARCHAR(50) CHECK (colore IN ('Bionda','Rossa','Scura')),
	quantitaBirra NUMBER NOT NULL,
	
	CONSTRAINT BIRRP_PK
		PRIMARY KEY(numLotto),
	CONSTRAINT BIRRP_FK2
		FOREIGN KEY(ssnSupervisore) REFERENCES MastroBirraio(ssn),		
	CONSTRAINT BIRRP_FK3
		FOREIGN KEY(numLottoMostoDolce) REFERENCES MostoDolce(numLotto)
);

CREATE TABLE Ammostamento(
	idBollitore NUMBER NOT NULL,
	dataAmmostamento DATE NOT NULL,
	gtinMalto NUMBER NOT NULL,
	codLottoMalto VARCHAR2(50) NOT NULL, 
	numLottoProdotto NUMBER NOT NULL,
	quantitaMalto NUMBER NOT NULL CHECK(quantitaMalto > 0),
	quantitaAcqua NUMBER NOT NULL CHECK(quantitaAcqua > 0),
	
	CONSTRAINT AMM_PK
		PRIMARY KEY (idBollitore,dataAmmostamento),
	CONSTRAINT AMM_FK_MALT	
		FOREIGN KEY(gtinMalto,codLottoMalto) REFERENCES MaltoAcquistato(GTIN,codiceLotto),
	CONSTRAINT AMM_FKPK_CONT
		FOREIGN KEY(idBollitore) REFERENCES Contenitore(id),
	CONSTRAINT AMM_FK_MSTDLC
		FOREIGN KEY(numLottoProdotto) REFERENCES MostoDolce(numLotto)
);

CREATE TABLE Fermentazione(
	idFermentatore NUMBER NOT NULL,
	dataInizio DATE NOT NULL,
	numLottoFermentato NUMBER,
	gtinLievitoUsato NUMBER NOT NULL,
	codLottoLievito VARCHAR2(50) NOT NULL, 
	numLottoBirraProdotta NUMBER,
	dataFine DATE,
	tipoFermentazione CHAR(20) CHECK(tipoFermentazione IN('Alta','Bassa')),
	
	CONSTRAINT FERM_PK
		PRIMARY KEY (idFermentatore,dataInizio),
	CONSTRAINT FERM_PKFK_CONT
		FOREIGN KEY(idFermentatore) REFERENCES Contenitore(id),
	CONSTRAINT FERM_FK_MD
		FOREIGN KEY(numLottoFermentato) REFERENCES MostoDolce(numLotto),
	CONSTRAINT FERM_FK_LA
		FOREIGN KEY(gtinLievitoUsato,codLottoLievito) REFERENCES LievitoAcquistato(GTIN,codiceLotto),
	CONSTRAINT FERM_FK_BIRRP
		FOREIGN KEY(numLottoBirraProdotta) REFERENCES BirraProdotta(numLotto)
);

CREATE TABLE PUB(
    particellaCatastale VARCHAR2(50) NOT NULL,
    nome CHAR(50) NOT NULL,
    citta CHAR(50) NOT NULL,
    via VARCHAR2(50) NOT NULL,
    cap NUMBER NOT NULL,
	
	CONSTRAINT PUB_PK
		PRIMARY KEY(particellaCatastale)
);


CREATE TABLE Vendita(
    codFattura VARCHAR2(50) NOT NULL,
    particellaCatastaleCliente VARCHAR2(50),
	metodoPagamento VARCHAR2(50),
	dataVendita DATE NOT NULL,
	
	CONSTRAINT V_PK
		PRIMARY KEY(codFattura),
	CONSTRAINT V_FK_PUB
		FOREIGN KEY(particellaCatastaleCliente) REFERENCES PUB(particellaCatastale)
);

CREATE TABLE BirraVenduta(
	numLotto NUMBER NOT NULL,
	codFattura VARCHAR2(50), 
	numFusti NUMBER,
	
	CONSTRAINT BV_PK
		PRIMARY KEY(numLotto,codFattura),
	CONSTRAINT BV_PKFK1
		FOREIGN KEY(numLotto) REFERENCES BirraProdotta(numLotto),
	CONSTRAINT BV_PKFK2
		FOREIGN KEY(codFattura) REFERENCES Vendita(codFattura)
	
);